### ISSUE TITLE
Markdown PR validation checklist

### ISSUE THREAD

**Issue by abhinavtripathy** [scalable-web-systems/main#3]
We need the following checks on a PR to be a merged:

- [x] The PR should only have markdown files - check for .md extension on files 
- [x] The markdown files needs to have a comment 
- [x] The comment in the markdown file needs to have tags in the comment
- [x] There needs to be a way to validate the tags - perhaps checking on whether the word exists in some sort of dictionary
- [x] Each image in the markdown needs to be validated

**Comment by abhinavtripathy** [comment]
https://stackoverflow.com/questions/839994/extracting-a-url-in-python
